services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    # Expose port only on debugging
    # ports:
    #   - "5432:5432"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    # Expose port only on debugging
    # ports:
    #   - "6379:6379"

  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - FIREBASE_LOGBOARD_CREDENTIALS_PATH=/app/credentials_logboard.json
      - FIREBASE_LOGMYSELF_CREDENTIALS_PATH=/app/credentials_logmyself.json
      - USE_FIREBASE_EMULATOR=${USE_FIREBASE_EMULATOR:-false}
      - FIREBASE_EMULATOR_HOST=${FIREBASE_EMULATOR_HOST:-127.0.0.1}
      - FIREBASE_EMULATOR_PORT=${FIREBASE_EMULATOR_PORT:-8080}

  celery_worker:
    build: .
    command: celery -A app.celery_app worker --loglevel=info --concurrency=4
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    restart: unless-stopped
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - FIREBASE_LOGBOARD_CREDENTIALS_PATH=/app/credentials_logboard.json
      - FIREBASE_LOGMYSELF_CREDENTIALS_PATH=/app/credentials_logmyself.json
      - USE_FIREBASE_EMULATOR=${USE_FIREBASE_EMULATOR:-false}
      - FIREBASE_EMULATOR_HOST=${FIREBASE_EMULATOR_HOST:-127.0.0.1}
      - FIREBASE_EMULATOR_PORT=${FIREBASE_EMULATOR_PORT:-8080}

  celery_beat:
    build: .
    command: celery -A app.celery_app beat --loglevel=info
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app
    restart: unless-stopped
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - FIREBASE_LOGBOARD_CREDENTIALS_PATH=/app/credentials_logboard.json
      - FIREBASE_LOGMYSELF_CREDENTIALS_PATH=/app/credentials_logmyself.json
      - USE_FIREBASE_EMULATOR=${USE_FIREBASE_EMULATOR:-false}
      - FIREBASE_EMULATOR_HOST=${FIREBASE_EMULATOR_HOST:-127.0.0.1}
      - FIREBASE_EMULATOR_PORT=${FIREBASE_EMULATOR_PORT:-8080}

  flower:
    build: .
    command: celery -A app.celery_app flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    restart: unless-stopped

volumes:
  postgres_data: